-- CreateTable
CREATE TABLE "public"."users" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user',
    "phone" TEXT,
    "city" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."applications" (
    "id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'submitted',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "adminComment" TEXT,
    "isPaid" BOOLEAN NOT NULL DEFAULT false,
    "paymentAmount" INTEGER,
    "paidAt" TIMESTAMP(3),
    "currentStage" INTEGER NOT NULL DEFAULT 1,
    "totalStages" INTEGER NOT NULL DEFAULT 10,
    "isFirstFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isSecondFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isThirdFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isFourthFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isFifthFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isSixthFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isSeventhFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isEighthFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isNinthFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isTenthFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isParentGuardianFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isCaregiverFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "isOutsiderFormCompleted" BOOLEAN NOT NULL DEFAULT false,
    "parentFullName" TEXT NOT NULL,
    "parentEmail" TEXT NOT NULL,
    "parentPhone" TEXT,
    "relationToChild" TEXT,
    "parentCity" TEXT,
    "parentEthnicity" TEXT,
    "childFullName" TEXT NOT NULL,
    "childDateOfBirth" TIMESTAMP(3),
    "childAge" INTEGER,
    "childGender" TEXT,
    "childEthnicity" TEXT,
    "childSchoolYear" TEXT,
    "childCurrentSchool" TEXT,
    "childSchoolType" TEXT,
    "childSchoolTypeOther" TEXT,
    "childDiagnosedNeeds" TEXT,
    "caregiverFullName" TEXT,
    "caregiverPhone" TEXT,
    "qExcitesMost" TEXT NOT NULL,
    "qNonTraditionalReason" TEXT NOT NULL,
    "qBiggestHope" TEXT NOT NULL,
    "enjoysTech" TEXT NOT NULL,
    "enjoysHandsOn" TEXT NOT NULL,
    "consentContact" BOOLEAN NOT NULL,
    "consentUpdates" BOOLEAN NOT NULL,
    "consentBiometric" BOOLEAN,
    "userId" INTEGER,

    CONSTRAINT "applications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."user_requests" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "user_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."screening_calls" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "fullName" TEXT NOT NULL,
    "childName" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "callerName" TEXT NOT NULL,
    "crmLeadTag" TEXT,
    "recordingPermission" TEXT,
    "introductionNotes" TEXT,
    "overviewNotes" TEXT,
    "applicationReason" TEXT,
    "currentSchoolIssues" TEXT,
    "techResponseAtHome" TEXT,
    "parentWarmUpNotes" TEXT,
    "flexibleModelOpenness" TEXT,
    "childFreeTime" TEXT,
    "adaptiveTechComfort" TEXT,
    "fitClarificationNotes" TEXT,
    "generalNotes" TEXT,
    "parentReactionsNotes" TEXT,
    "comprehensiveQuestionnaires" BOOLEAN NOT NULL DEFAULT false,
    "guidebookInfo" BOOLEAN NOT NULL DEFAULT false,
    "walkthroughDate" TEXT,
    "assessmentInvite" TEXT,
    "additionalNotes" TEXT,
    "applicationId" TEXT NOT NULL,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,

    CONSTRAINT "screening_calls_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."parent_guardian_questionnaires" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "fullName" TEXT NOT NULL,
    "childName" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "typicalWeekday" TEXT NOT NULL,
    "screenTimeHours" TEXT NOT NULL,
    "homeActivities" TEXT NOT NULL,
    "culturalBackground" TEXT NOT NULL,
    "rulesDisciplineApproach" TEXT NOT NULL,
    "supportWhenStruggling" TEXT NOT NULL,
    "strengthsInterests" TEXT NOT NULL,
    "challengingAreas" TEXT NOT NULL,
    "learningApproach" TEXT NOT NULL,
    "previousEducationalExperience" TEXT NOT NULL,
    "covidLearningExperience" TEXT NOT NULL,
    "supportiveLearningEnvironment" TEXT NOT NULL,
    "responseToFrustration" TEXT NOT NULL,
    "peerInteraction" TEXT NOT NULL,
    "emotionalBehavioralConcerns" TEXT NOT NULL,
    "seekingHelp" TEXT NOT NULL,
    "educationalHopesGoals" TEXT NOT NULL,
    "creativityMovementEmotionalRole" TEXT NOT NULL,
    "parentingStyle" TEXT NOT NULL,
    "technologyConcerns" TEXT NOT NULL,
    "applicationNumber" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "applicationId" TEXT NOT NULL,

    CONSTRAINT "parent_guardian_questionnaires_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."caregiver_questionnaires" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "fullName" TEXT NOT NULL,
    "childName" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "careDuration" TEXT NOT NULL,
    "regularActivities" TEXT NOT NULL,
    "behaviorWithoutParent" TEXT NOT NULL,
    "toysGamesTasksEnjoyed" TEXT NOT NULL,
    "preferences" TEXT NOT NULL,
    "responseToDifficulties" TEXT NOT NULL,
    "engagementWithChosenActivity" TEXT NOT NULL,
    "engagementWithAssignedActivity" TEXT NOT NULL,
    "interactionWithChildren" TEXT NOT NULL,
    "seekingHelpComfort" TEXT NOT NULL,
    "emotionalRegulationStrategies" TEXT NOT NULL,
    "emotionalStrengthsVulnerabilities" TEXT NOT NULL,
    "applicationNumber" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "applicationId" TEXT NOT NULL,

    CONSTRAINT "caregiver_questionnaires_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."outsider_questionnaires" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "fullName" TEXT NOT NULL,
    "childName" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "relationshipToChild" TEXT NOT NULL,
    "interactionContext" TEXT NOT NULL,
    "learningTendenciesCuriosity" TEXT NOT NULL,
    "emotionalTraits" TEXT NOT NULL,
    "adaptationToChanges" TEXT NOT NULL,
    "communicationSkills" TEXT NOT NULL,
    "groupBehavior" TEXT NOT NULL,
    "concernsNotes" TEXT NOT NULL,
    "emotionalStrengthsVulnerabilities" TEXT NOT NULL,
    "applicationNumber" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "applicationId" TEXT NOT NULL,

    CONSTRAINT "outsider_questionnaires_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."facility_walkthrough_checklists" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "examinerName" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "welcomeOverviewCompleted" BOOLEAN NOT NULL DEFAULT false,
    "tourLearningZonesCompleted" BOOLEAN NOT NULL DEFAULT false,
    "technologyDemonstrationCompleted" BOOLEAN NOT NULL DEFAULT false,
    "safetySecurityMeasuresCompleted" BOOLEAN NOT NULL DEFAULT false,
    "qaSessionCompleted" BOOLEAN NOT NULL DEFAULT false,
    "scheduleAssessmentDatesCompleted" BOOLEAN NOT NULL DEFAULT false,
    "welcomeOverviewNotes" TEXT NOT NULL,
    "tourLearningZonesNotes" TEXT NOT NULL,
    "technologyDemonstrationNotes" TEXT NOT NULL,
    "safetySecurityMeasuresNotes" TEXT NOT NULL,
    "qaSessionNotes" TEXT NOT NULL,
    "scheduleAssessmentDatesNotes" TEXT NOT NULL,
    "applicationNumber" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "applicationId" TEXT NOT NULL,

    CONSTRAINT "facility_walkthrough_checklists_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."initial_observation_forms" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "fullName" TEXT NOT NULL,
    "age" TEXT NOT NULL,
    "date" TEXT NOT NULL DEFAULT '',
    "examiner" TEXT NOT NULL DEFAULT '',
    "zoneATimeSpent" TEXT NOT NULL,
    "zoneASelfDirected" TEXT NOT NULL,
    "zoneAObservations" TEXT NOT NULL,
    "zoneAEngagementLevel" TEXT NOT NULL,
    "zoneAKeyBehavioursNotes" TEXT NOT NULL,
    "zoneBTimeSpent" TEXT NOT NULL,
    "zoneBSelfDirected" TEXT NOT NULL,
    "zoneBObservations" TEXT NOT NULL,
    "zoneBEngagementLevel" TEXT NOT NULL,
    "zoneBKeyBehavioursNotes" TEXT NOT NULL,
    "zoneCTimeSpent" TEXT NOT NULL,
    "zoneCSelfDirected" TEXT NOT NULL,
    "zoneCObservations" TEXT NOT NULL,
    "zoneCEngagementLevel" TEXT NOT NULL,
    "zoneCKeyBehavioursNotes" TEXT NOT NULL,
    "zoneDTimeSpent" TEXT NOT NULL,
    "zoneDSelfDirected" TEXT NOT NULL,
    "zoneDObservations" TEXT NOT NULL,
    "zoneDEngagementLevel" TEXT NOT NULL,
    "zoneDKeyBehavioursNotes" TEXT NOT NULL,
    "selfRegulationObserved" TEXT NOT NULL,
    "selfRegulationBehaviourNotes" TEXT NOT NULL,
    "curiosityObserved" TEXT NOT NULL,
    "curiosityBehaviourNotes" TEXT NOT NULL,
    "socialEngagementObserved" TEXT NOT NULL,
    "socialEngagementBehaviourNotes" TEXT NOT NULL,
    "emotionalRegulationObserved" TEXT NOT NULL,
    "emotionalRegulationBehaviourNotes" TEXT NOT NULL,
    "confidenceAutonomyObserved" TEXT NOT NULL,
    "confidenceAutonomyBehaviourNotes" TEXT NOT NULL,
    "linguisticEvidence" TEXT NOT NULL,
    "linguisticSupportingObservation" TEXT NOT NULL,
    "logicalMathematicalEvidence" TEXT NOT NULL,
    "logicalMathematicalSupportingObservation" TEXT NOT NULL,
    "spatialEvidence" TEXT NOT NULL,
    "spatialSupportingObservation" TEXT NOT NULL,
    "bodilyKinestheticEvidence" TEXT NOT NULL,
    "bodilyKinestheticSupportingObservation" TEXT NOT NULL,
    "musicalEvidence" TEXT NOT NULL,
    "musicalSupportingObservation" TEXT NOT NULL,
    "existentialEvidence" TEXT NOT NULL DEFAULT '',
    "existentialSupportingObservation" TEXT NOT NULL DEFAULT '',
    "interpersonalEvidence" TEXT NOT NULL,
    "interpersonalSupportingObservation" TEXT NOT NULL,
    "intrapersonalEvidence" TEXT NOT NULL,
    "intrapersonalSupportingObservation" TEXT NOT NULL,
    "naturalisticEvidence" TEXT NOT NULL,
    "naturalisticSupportingObservation" TEXT NOT NULL,
    "parentProximity" TEXT NOT NULL,
    "parentInterventionLevel" TEXT NOT NULL,
    "parentInterventionStyle" TEXT NOT NULL,
    "childIndependenceLevel" TEXT NOT NULL,
    "childEmotionalPresentationWithParent" TEXT NOT NULL,
    "childIndependenceWhenParentEngaged" TEXT NOT NULL,
    "emotionalRegulationWithParentPresent" TEXT NOT NULL,
    "mostEngagedZone" TEXT NOT NULL,
    "dominantObservedIntelligences" TEXT NOT NULL,
    "initialLearningStyleImpressions" TEXT NOT NULL,
    "earlyFlagsNeedsFollowUp" TEXT NOT NULL,
    "selfDirectedVsSeekingGuidance" TEXT NOT NULL,
    "flagIndicators" TEXT NOT NULL,
    "additionalNotesObservations" TEXT NOT NULL,
    "applicationNumber" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "applicationId" TEXT NOT NULL,

    CONSTRAINT "initial_observation_forms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."guided_observations_procedures" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "fullName" TEXT NOT NULL,
    "age" TEXT NOT NULL,
    "zoneAScore" TEXT NOT NULL,
    "zoneANotes" TEXT NOT NULL,
    "zoneBScore" TEXT NOT NULL,
    "zoneBNotes" TEXT NOT NULL,
    "zoneCScore" TEXT NOT NULL,
    "zoneCNotes" TEXT NOT NULL,
    "zoneDScore" TEXT NOT NULL,
    "zoneDNotes" TEXT NOT NULL,
    "guidingQ1" TEXT,
    "guidingQ2" TEXT,
    "guidingQ3" TEXT,
    "guidingQ4" TEXT,
    "guidingQ5" TEXT,
    "areaLikeBest" TEXT,
    "whatMakesInteresting" TEXT,
    "hardButFun" TEXT,
    "feelWhenTryingNew" TEXT,
    "teachGame" TEXT,
    "metaSelfReg" TEXT NOT NULL,
    "metaNotesSelfReg" TEXT,
    "metaCuriosity" TEXT NOT NULL,
    "metaNotesCuriosity" TEXT,
    "metaSocial" TEXT NOT NULL,
    "metaNotesSocial" TEXT,
    "metaEmotional" TEXT NOT NULL,
    "metaNotesEmotional" TEXT,
    "metaConfidence" TEXT NOT NULL,
    "metaNotesConfidence" TEXT,
    "intelLinguistic" TEXT,
    "intelLogical" TEXT,
    "intelSpatial" TEXT,
    "intelBodily" TEXT,
    "intelMusical" TEXT,
    "intelInterpersonal" TEXT,
    "intelIntrapersonal" TEXT,
    "intelNaturalistic" TEXT,
    "intelExistential" TEXT,
    "intelLinguisticEvidenceModerate" BOOLEAN DEFAULT false,
    "intelLinguisticEvidenceStrong" BOOLEAN DEFAULT false,
    "intelLogicalEvidenceModerate" BOOLEAN DEFAULT false,
    "intelLogicalEvidenceStrong" BOOLEAN DEFAULT false,
    "intelSpatialEvidenceModerate" BOOLEAN DEFAULT false,
    "intelSpatialEvidenceStrong" BOOLEAN DEFAULT false,
    "intelBodilyEvidenceModerate" BOOLEAN DEFAULT false,
    "intelBodilyEvidenceStrong" BOOLEAN DEFAULT false,
    "intelMusicalEvidenceModerate" BOOLEAN DEFAULT false,
    "intelMusicalEvidenceStrong" BOOLEAN DEFAULT false,
    "intelInterpersonalEvidenceModerate" BOOLEAN DEFAULT false,
    "intelInterpersonalEvidenceStrong" BOOLEAN DEFAULT false,
    "intelIntrapersonalEvidenceModerate" BOOLEAN DEFAULT false,
    "intelIntrapersonalEvidenceStrong" BOOLEAN DEFAULT false,
    "intelNaturalisticEvidenceModerate" BOOLEAN DEFAULT false,
    "intelNaturalisticEvidenceStrong" BOOLEAN DEFAULT false,
    "intelExistentialEvidenceModerate" BOOLEAN DEFAULT false,
    "intelExistentialEvidenceStrong" BOOLEAN DEFAULT false,
    "parentProximity" TEXT,
    "parentInterventionLevel" TEXT,
    "parentInterventionStyle" TEXT,
    "childIndependenceLevel" TEXT,
    "childEmotionalWithParent" TEXT,
    "childIndependenceWhenParentEngaged" TEXT,
    "emotionalRegulationWithParentPresent" TEXT,
    "mostEngagedZone" TEXT,
    "dominantObservedIntelligences" TEXT,
    "initialLearningStyleImpressions" TEXT,
    "earlyFlagsNeedsFollowUp" TEXT,
    "selfDirectedVsSeekingGuidance" TEXT,
    "finalAdditionalNotes" TEXT,
    "interactionPreferredZone" TEXT,
    "interactionInitialBehaviour" TEXT,
    "interactionOpennessToAdultGuidance" TEXT,
    "interactionMostRevealingActivity" TEXT,
    "interactionCrossRefStep5" TEXT,
    "interactionCuriosityExploration" TEXT,
    "interactionFocusAttention" TEXT,
    "interactionEngagementWithAdult" TEXT,
    "interactionResilienceInChallenge" TEXT,
    "interactionEmotionRegulationSignals" TEXT,
    "interactionCaregiverInteractionStyle" TEXT,
    "interactionRecommendations" TEXT,
    "applicationNumber" TEXT,
    "observerName" TEXT,
    "assessmentDate" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "applicationId" TEXT NOT NULL,

    CONSTRAINT "guided_observations_procedures_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ks1_interview_questions" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "fullName" TEXT NOT NULL,
    "age" TEXT NOT NULL,
    "whatDoYouDoSomethingHard" INTEGER,
    "whatDoYouDoSomethingHardNotes" TEXT,
    "howDoYouFeelWhenTryNew" INTEGER,
    "howDoYouFeelWhenTryNewNotes" TEXT,
    "whatWouldYouDoIfFriendSad" INTEGER,
    "whatWouldYouDoIfFriendSadNotes" TEXT,
    "tellMeAboutFavouriteStory" INTEGER,
    "tellMeAboutFavouriteStoryNotes" TEXT,
    "favouriteThingToLearn" INTEGER,
    "favouriteThingToLearnNotes" TEXT,
    "whatElseUcanDoWithASpoonOtherThanEat" INTEGER,
    "whatElseUcanDoWithASpoonOtherThanEatNotes" TEXT,
    "howShareCookiesBetweenFriends" INTEGER,
    "howShareCookiesBetweenFriendsNotes" TEXT,
    "puzzleActivity" INTEGER,
    "puzzleActivityNotes" TEXT,
    "tableInteraction" INTEGER,
    "tableInteractionNotes" TEXT,
    "drawSomethingYouInvent" INTEGER,
    "drawSomethingYouInventNotes" TEXT,
    "doYouLikeLearnByListening" TEXT,
    "canYouSortShapesByColor" INTEGER,
    "canYouSortShapesByColorNotes" TEXT,
    "canYouTeachMeDrawMummy" INTEGER,
    "canYouTeachMeDrawMummyNotes" TEXT,
    "doYouLikePlayingWithFriends" INTEGER,
    "doYouLikePlayingWithFriendsNotes" TEXT,
    "parentalInterferenceFlagged" BOOLEAN NOT NULL DEFAULT false,
    "parentalInterferenceNotes" TEXT,
    "totalScore" INTEGER,
    "applicationNumber" TEXT,
    "observerName" TEXT,
    "assessmentDate" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "applicationId" TEXT NOT NULL,

    CONSTRAINT "ks1_interview_questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ks2_interview_questions" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "fullName" TEXT,
    "age" TEXT,
    "somethingAlwaysWantedToLearn" INTEGER,
    "somethingAlwaysWantedToLearnNotes" TEXT,
    "fiveThingsWithPaperclip" INTEGER,
    "fiveThingsWithPaperclipNotes" TEXT,
    "finishSchoolworkEarly" INTEGER,
    "finishSchoolworkEarlyNotes" TEXT,
    "logicChallenge" INTEGER,
    "logicChallengeNotes" TEXT,
    "somethingHard" INTEGER,
    "somethingHardNotes" TEXT,
    "answerIsWrong" INTEGER,
    "answerIsWrongNotes" TEXT,
    "favouriteThingOnComputer" INTEGER,
    "favouriteThingOnComputerNotes" TEXT,
    "likeWorkingWithOthers" INTEGER,
    "likeWorkingWithOthersNotes" TEXT,
    "drawMachineInvention" INTEGER,
    "drawMachineInventionNotes" TEXT,
    "confidenceTryingNewThings" INTEGER,
    "confidenceTryingNewThingsNotes" TEXT,
    "helpedSomeoneLearn" INTEGER,
    "helpedSomeoneLearnNotes" TEXT,
    "magicWandMakesSmarter" INTEGER,
    "magicWandMakesSmarterNotes" TEXT,
    "explainInternetToPast" INTEGER,
    "explainInternetToPastNotes" TEXT,
    "inChargeOfWorld" INTEGER,
    "inChargeOfWorldNotes" TEXT,
    "threeThingsGoodAt" INTEGER,
    "threeThingsGoodAtNotes" TEXT,
    "somethingGetBetterAt" INTEGER,
    "somethingGetBetterAtNotes" TEXT,
    "inventJobDoesntExist" INTEGER,
    "inventJobDoesntExistNotes" TEXT,
    "learningPreference" TEXT,
    "digitalTasks" INTEGER,
    "digitalTasksNotes" TEXT,
    "playingWithFriends" INTEGER,
    "playingWithFriendsNotes" TEXT,
    "parentalInterferenceFlagged" BOOLEAN NOT NULL DEFAULT false,
    "parentalInterferenceNotes" TEXT,
    "totalScore" INTEGER,
    "applicationNumber" TEXT,
    "observerName" TEXT,
    "assessmentDate" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ks2_interview_questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."peer_dynamic_observation" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "childName" TEXT,
    "date" TEXT,
    "examiner" TEXT,
    "age" TEXT,
    "sessionStartTime" TEXT,
    "sessionEndTime" TEXT,
    "leadershipRating" INTEGER,
    "leadershipNotes" TEXT,
    "collaborationRating" INTEGER,
    "collaborationNotes" TEXT,
    "conflictResolutionRating" INTEGER,
    "conflictResolutionNotes" TEXT,
    "communicationRating" INTEGER,
    "communicationNotes" TEXT,
    "emotionalRegulationRating" INTEGER,
    "emotionalRegulationNotes" TEXT,
    "empathyRating" INTEGER,
    "empathyNotes" TEXT,
    "adaptabilityRating" INTEGER,
    "adaptabilityNotes" TEXT,
    "initiativeRating" INTEGER,
    "initiativeNotes" TEXT,
    "curiosityObserved" BOOLEAN NOT NULL DEFAULT false,
    "curiosityNotes" TEXT,
    "confidenceObserved" BOOLEAN NOT NULL DEFAULT false,
    "confidenceNotes" TEXT,
    "selfRegulationObserved" BOOLEAN NOT NULL DEFAULT false,
    "selfRegulationNotes" TEXT,
    "collaborationObserved" BOOLEAN NOT NULL DEFAULT false,
    "collaborationObservedNotes" TEXT,
    "emotionalAwarenessObserved" BOOLEAN NOT NULL DEFAULT false,
    "emotionalAwarenessNotes" TEXT,
    "leadershipObserved" BOOLEAN NOT NULL DEFAULT false,
    "leadershipObservedNotes" TEXT,
    "problemSolvingObserved" BOOLEAN NOT NULL DEFAULT false,
    "problemSolvingNotes" TEXT,
    "perspectiveTakingObserved" BOOLEAN NOT NULL DEFAULT false,
    "perspectiveTakingNotes" TEXT,
    "linguisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "linguisticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "linguisticNotes" TEXT,
    "logicalMathematicalObserved" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalNotes" TEXT,
    "spatialObserved" BOOLEAN NOT NULL DEFAULT false,
    "spatialStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "spatialNotes" TEXT,
    "bodilyKinestheticObserved" BOOLEAN NOT NULL DEFAULT false,
    "bodilyKinestheticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "bodilyKinestheticNotes" TEXT,
    "musicalObserved" BOOLEAN NOT NULL DEFAULT false,
    "musicalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "musicalNotes" TEXT,
    "interpersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "interpersonalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "interpersonalNotes" TEXT,
    "intrapersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "intrapersonalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "intrapersonalNotes" TEXT,
    "naturalisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "naturalisticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "naturalisticNotes" TEXT,
    "existentialObserved" BOOLEAN NOT NULL DEFAULT false,
    "existentialStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "existentialNotes" TEXT,
    "visualObserved" BOOLEAN NOT NULL DEFAULT false,
    "visualNotes" TEXT,
    "auditoryObserved" BOOLEAN NOT NULL DEFAULT false,
    "auditoryNotes" TEXT,
    "kinestheticObserved" BOOLEAN NOT NULL DEFAULT false,
    "kinestheticNotes" TEXT,
    "verbalObserved" BOOLEAN NOT NULL DEFAULT false,
    "verbalNotes" TEXT,
    "socialObserved" BOOLEAN NOT NULL DEFAULT false,
    "socialNotes" TEXT,
    "solitaryObserved" BOOLEAN NOT NULL DEFAULT false,
    "solitaryNotes" TEXT,
    "leaderRole" BOOLEAN NOT NULL DEFAULT false,
    "withdrawnRole" BOOLEAN NOT NULL DEFAULT false,
    "problemSolverRole" BOOLEAN NOT NULL DEFAULT false,
    "followerRole" BOOLEAN NOT NULL DEFAULT false,
    "initiatorRole" BOOLEAN NOT NULL DEFAULT false,
    "bridgerRole" BOOLEAN NOT NULL DEFAULT false,
    "observerRole" BOOLEAN NOT NULL DEFAULT false,
    "supporterRole" BOOLEAN NOT NULL DEFAULT false,
    "challengerRole" BOOLEAN NOT NULL DEFAULT false,
    "mediatorRole" BOOLEAN NOT NULL DEFAULT false,
    "notableStrengths" TEXT,
    "areasOfConcern" TEXT,
    "situationsChildThrived" TEXT,
    "situationsChallenging" TEXT,
    "suggestedFollowUp" TEXT,
    "caregiverInteraction" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "peer_dynamic_observation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."parent_child_dynamic_observation" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "childFullName" TEXT,
    "childAge" TEXT,
    "sharedIdeaExchangeRating" INTEGER,
    "sharedIdeaExchangeNotes" TEXT,
    "emotionalWarmthRating" INTEGER,
    "emotionalWarmthNotes" TEXT,
    "balanceOfLeadershipRating" INTEGER,
    "balanceOfLeadershipNotes" TEXT,
    "communicationStyleRating" INTEGER,
    "communicationStyleNotes" TEXT,
    "mutualCreativityRating" INTEGER,
    "mutualCreativityNotes" TEXT,
    "independenceRating" INTEGER,
    "independenceNotes" TEXT,
    "confidenceHesitationRating" INTEGER,
    "confidenceHesitationNotes" TEXT,
    "taskEngagementRating" INTEGER,
    "taskEngagementNotes" TEXT,
    "creativeExpansionRating" INTEGER,
    "creativeExpansionNotes" TEXT,
    "teachingStyleRating" INTEGER,
    "teachingStyleNotes" TEXT,
    "patienceEncouragementRating" INTEGER,
    "patienceEncouragementNotes" TEXT,
    "parentClarityRating" INTEGER,
    "parentClarityNotes" TEXT,
    "childEngagementRating" INTEGER,
    "childEngagementNotes" TEXT,
    "parentDominantStyleDirective" BOOLEAN NOT NULL DEFAULT false,
    "parentDominantStyleSupportive" BOOLEAN NOT NULL DEFAULT false,
    "parentDominantStyleDetached" BOOLEAN NOT NULL DEFAULT false,
    "parentDominantStyleFacilitative" BOOLEAN NOT NULL DEFAULT false,
    "emotionalAttunementHigh" BOOLEAN NOT NULL DEFAULT false,
    "emotionalAttunementModerate" BOOLEAN NOT NULL DEFAULT false,
    "emotionalAttunementLow" BOOLEAN NOT NULL DEFAULT false,
    "encouragementStylePraiseFocused" BOOLEAN NOT NULL DEFAULT false,
    "encouragementStyleProcessFocused" BOOLEAN NOT NULL DEFAULT false,
    "encouragementStyleCorrectionFocused" BOOLEAN NOT NULL DEFAULT false,
    "attachmentSignalSecure" BOOLEAN NOT NULL DEFAULT false,
    "attachmentSignalAnxious" BOOLEAN NOT NULL DEFAULT false,
    "attachmentSignalAvoidant" BOOLEAN NOT NULL DEFAULT false,
    "attachmentSignalDisengaged" BOOLEAN NOT NULL DEFAULT false,
    "confidenceAutonomyObserved" BOOLEAN NOT NULL DEFAULT false,
    "confidenceAutonomyNotes" TEXT,
    "emotionalRegulationObserved" BOOLEAN NOT NULL DEFAULT false,
    "emotionalRegulationNotes" TEXT,
    "curiosityObserved" BOOLEAN NOT NULL DEFAULT false,
    "curiosityNotes" TEXT,
    "creativityExpressionObserved" BOOLEAN NOT NULL DEFAULT false,
    "creativityExpressionNotes" TEXT,
    "selfDirectedLearningObserved" BOOLEAN NOT NULL DEFAULT false,
    "selfDirectedLearningNotes" TEXT,
    "communicationObserved" BOOLEAN NOT NULL DEFAULT false,
    "communicationNotes" TEXT,
    "linguisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "linguisticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "linguisticNotes" TEXT,
    "logicalMathematicalObserved" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalNotes" TEXT,
    "spatialObserved" BOOLEAN NOT NULL DEFAULT false,
    "spatialStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "spatialNotes" TEXT,
    "bodilyKinestheticObserved" BOOLEAN NOT NULL DEFAULT false,
    "bodilyKinestheticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "bodilyKinestheticNotes" TEXT,
    "musicalObserved" BOOLEAN NOT NULL DEFAULT false,
    "musicalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "musicalNotes" TEXT,
    "interpersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "interpersonalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "interpersonalNotes" TEXT,
    "intrapersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "intrapersonalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "intrapersonalNotes" TEXT,
    "naturalisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "naturalisticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "naturalisticNotes" TEXT,
    "existentialObserved" BOOLEAN NOT NULL DEFAULT false,
    "existentialStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "existentialNotes" TEXT,
    "parentChildDynamicStandout" TEXT,
    "childExpressiveWithWithoutParent" TEXT,
    "parentGuidanceHindrance" TEXT,
    "emotionalDistressFlag" BOOLEAN NOT NULL DEFAULT false,
    "parentOverDirectionFlag" BOOLEAN NOT NULL DEFAULT false,
    "confidenceIssueFlag" BOOLEAN NOT NULL DEFAULT false,
    "noFlagsFlag" BOOLEAN NOT NULL DEFAULT false,
    "redFlagsNotes" TEXT,
    "applicationNumber" TEXT,
    "observerName" TEXT,
    "assessmentDate" TEXT,
    "loggedToSystemDate" TEXT,
    "loggedBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "parent_child_dynamic_observation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."comprehensive_profile_sheet" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "childName" TEXT,
    "childAge" TEXT,
    "assessmentDate" TEXT,
    "recommendedPlacement" TEXT,
    "examiner" TEXT,
    "processingSpeedSteadyReflective" BOOLEAN NOT NULL DEFAULT false,
    "processingSpeedFlexibleAdaptive" BOOLEAN NOT NULL DEFAULT false,
    "processingSpeedRapidResponsive" BOOLEAN NOT NULL DEFAULT false,
    "workingMemoryAreaOfGrowth" BOOLEAN NOT NULL DEFAULT false,
    "workingMemoryDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "workingMemoryConsistentConfident" BOOLEAN NOT NULL DEFAULT false,
    "attentionFocusVariable" BOOLEAN NOT NULL DEFAULT false,
    "attentionFocusFocusedWithCues" BOOLEAN NOT NULL DEFAULT false,
    "attentionFocusSelfDirected" BOOLEAN NOT NULL DEFAULT false,
    "verbalReasoningExploring" BOOLEAN NOT NULL DEFAULT false,
    "verbalReasoningDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "verbalReasoningFluentCommunicator" BOOLEAN NOT NULL DEFAULT false,
    "phonologicalAwarenessExploring" BOOLEAN NOT NULL DEFAULT false,
    "phonologicalAwarenessLinking" BOOLEAN NOT NULL DEFAULT false,
    "phonologicalAwarenessConfident" BOOLEAN NOT NULL DEFAULT false,
    "visualSpatialSkillsExploring" BOOLEAN NOT NULL DEFAULT false,
    "visualSpatialSkillsDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "visualSpatialSkillsConfident" BOOLEAN NOT NULL DEFAULT false,
    "numericalPatternConcrete" BOOLEAN NOT NULL DEFAULT false,
    "numericalPatternEmergingAbstract" BOOLEAN NOT NULL DEFAULT false,
    "numericalPatternFlexibleThinker" BOOLEAN NOT NULL DEFAULT false,
    "additionalCognitiveNotes" TEXT,
    "visualObserved" BOOLEAN NOT NULL DEFAULT false,
    "visualObservedEvidence" TEXT,
    "auditoryObserved" BOOLEAN NOT NULL DEFAULT false,
    "auditoryObservedEvidence" TEXT,
    "kinestheticTactileObserved" BOOLEAN NOT NULL DEFAULT false,
    "kinestheticTactileObservedEvidence" TEXT,
    "readingWritingObserved" BOOLEAN NOT NULL DEFAULT false,
    "readingWritingObservedEvidence" TEXT,
    "verbalLinguisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "verbalLinguisticObservedEvidence" TEXT,
    "logicalMathematicalObserved" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalObservedEvidence" TEXT,
    "socialInterpersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "socialInterpersonalObservedEvidence" TEXT,
    "solitaryIntrapersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "solitaryIntrapersonalObservedEvidence" TEXT,
    "multimodalObserved" BOOLEAN NOT NULL DEFAULT false,
    "multimodalObservedEvidence" TEXT,
    "linguisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "linguisticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "linguisticNotes" TEXT,
    "logicalMathematicalObservedInt" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalStronglyEvidentInt" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalNotesInt" TEXT,
    "spatialObserved" BOOLEAN NOT NULL DEFAULT false,
    "spatialStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "spatialNotes" TEXT,
    "bodilyKinestheticObserved" BOOLEAN NOT NULL DEFAULT false,
    "bodilyKinestheticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "bodilyKinestheticNotes" TEXT,
    "musicalObserved" BOOLEAN NOT NULL DEFAULT false,
    "musicalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "musicalNotes" TEXT,
    "interpersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "interpersonalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "interpersonalNotes" TEXT,
    "intrapersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "intrapersonalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "intrapersonalNotes" TEXT,
    "naturalisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "naturalisticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "naturalisticNotes" TEXT,
    "existentialObserved" BOOLEAN NOT NULL DEFAULT false,
    "existentialStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "existentialNotes" TEXT,
    "summaryInsightLearnerType" TEXT,
    "summaryInsightLearningEnvironments" TEXT,
    "selfRegulationEmerging" BOOLEAN NOT NULL DEFAULT false,
    "selfRegulationDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "selfRegulationStrong" BOOLEAN NOT NULL DEFAULT false,
    "selfRegulationNotesEvidence" TEXT,
    "emotionalIntelligenceEmerging" BOOLEAN NOT NULL DEFAULT false,
    "emotionalIntelligenceDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "emotionalIntelligenceStrong" BOOLEAN NOT NULL DEFAULT false,
    "emotionalIntelligenceNotesEvidence" TEXT,
    "socialCommunicationEmerging" BOOLEAN NOT NULL DEFAULT false,
    "socialCommunicationDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "socialCommunicationStrong" BOOLEAN NOT NULL DEFAULT false,
    "socialCommunicationNotesEvidence" TEXT,
    "cognitiveFlexibilityEmerging" BOOLEAN NOT NULL DEFAULT false,
    "cognitiveFlexibilityDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "cognitiveFlexibilityStrong" BOOLEAN NOT NULL DEFAULT false,
    "cognitiveFlexibilityNotesEvidence" TEXT,
    "resilienceConfidenceEmerging" BOOLEAN NOT NULL DEFAULT false,
    "resilienceConfidenceDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "resilienceConfidenceStrong" BOOLEAN NOT NULL DEFAULT false,
    "resilienceConfidenceNotesEvidence" TEXT,
    "creativityExpressionEmerging" BOOLEAN NOT NULL DEFAULT false,
    "creativityExpressionDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "creativityExpressionStrong" BOOLEAN NOT NULL DEFAULT false,
    "creativityExpressionNotesEvidence" TEXT,
    "softSkillSummaryNotes" TEXT,
    "englishCurrentLevel" TEXT,
    "englishNotes" TEXT,
    "mathsCurrentLevel" TEXT,
    "mathsNotes" TEXT,
    "scienceCurrentLevel" TEXT,
    "scienceNotes" TEXT,
    "technologyUseLow" BOOLEAN NOT NULL DEFAULT false,
    "technologyUseModerate" BOOLEAN NOT NULL DEFAULT false,
    "technologyUseHigh" BOOLEAN NOT NULL DEFAULT false,
    "technologyUseExceptional" BOOLEAN NOT NULL DEFAULT false,
    "academicNotes" TEXT,
    "zonesADPreferredZones" TEXT,
    "zonesADSelfDirectedOrReliant" TEXT,
    "zonesADResponseToChallenge" TEXT,
    "zonesADEvidenceDominantIntelligence" TEXT,
    "peerSessionInitiateOrFollow" TEXT,
    "peerSessionRoleAdopted" TEXT,
    "peerSessionConflictHandled" TEXT,
    "parentChildEmotionalTone" TEXT,
    "parentChildFacilitativeVsDirective" TEXT,
    "parentChildResponseWorkingSolo" TEXT,
    "ks1Score" INTEGER,
    "ks1InterpretationEmerging" BOOLEAN NOT NULL DEFAULT false,
    "ks1InterpretationBasic" BOOLEAN NOT NULL DEFAULT false,
    "ks1InterpretationStrong" BOOLEAN NOT NULL DEFAULT false,
    "ks1InterpretationExceptional" BOOLEAN NOT NULL DEFAULT false,
    "ks1SuggestedAction" TEXT,
    "ks1ScoreRange1325Action" TEXT,
    "ks1ScoreRange2640Action" TEXT,
    "ks1ScoreRange4155Action" TEXT,
    "ks1ScoreRange5665Action" TEXT,
    "ks2Score" INTEGER,
    "ks2InterpretationEmerging" BOOLEAN NOT NULL DEFAULT false,
    "ks2InterpretationBasic" BOOLEAN NOT NULL DEFAULT false,
    "ks2InterpretationStrong" BOOLEAN NOT NULL DEFAULT false,
    "ks2InterpretationExceptional" BOOLEAN NOT NULL DEFAULT false,
    "ks2SuggestedAction" TEXT,
    "ks2ScoreRange2044Action" TEXT,
    "ks2ScoreRange4569Action" TEXT,
    "ks2ScoreRange7089Action" TEXT,
    "ks2ScoreRange9095Action" TEXT,
    "qualitativeInsightsVerbalResponses" TEXT,
    "aiCurriculumEntryPoint" TEXT,
    "peerEngagementGroupLearning" BOOLEAN NOT NULL DEFAULT false,
    "peerEngagementNeedsScaffolding" BOOLEAN NOT NULL DEFAULT false,
    "peerEngagementMonitorConflict" BOOLEAN NOT NULL DEFAULT false,
    "mentorshipLeadershipPotential" BOOLEAN NOT NULL DEFAULT false,
    "mentorshipRecommendOneOnOne" BOOLEAN NOT NULL DEFAULT false,
    "mentorshipNotApplicable" BOOLEAN NOT NULL DEFAULT false,
    "homeSupportTips" TEXT,
    "finalSummaryStrengths" TEXT,
    "finalSummaryApproaches" TEXT,
    "finalSummaryTargetedSupport" TEXT,
    "compiledBy" TEXT,
    "compiledDate" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "comprehensive_profile_sheet_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "public"."users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "screening_calls_applicationId_key" ON "public"."screening_calls"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "parent_guardian_questionnaires_applicationId_key" ON "public"."parent_guardian_questionnaires"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "caregiver_questionnaires_applicationId_key" ON "public"."caregiver_questionnaires"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "outsider_questionnaires_applicationId_key" ON "public"."outsider_questionnaires"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "facility_walkthrough_checklists_applicationId_key" ON "public"."facility_walkthrough_checklists"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "initial_observation_forms_applicationId_key" ON "public"."initial_observation_forms"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "guided_observations_procedures_applicationId_key" ON "public"."guided_observations_procedures"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "ks1_interview_questions_applicationId_key" ON "public"."ks1_interview_questions"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "ks2_interview_questions_applicationId_key" ON "public"."ks2_interview_questions"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "peer_dynamic_observation_applicationId_key" ON "public"."peer_dynamic_observation"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "parent_child_dynamic_observation_applicationId_key" ON "public"."parent_child_dynamic_observation"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "comprehensive_profile_sheet_applicationId_key" ON "public"."comprehensive_profile_sheet"("applicationId");

-- AddForeignKey
ALTER TABLE "public"."applications" ADD CONSTRAINT "applications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."user_requests" ADD CONSTRAINT "user_requests_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."screening_calls" ADD CONSTRAINT "screening_calls_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."parent_guardian_questionnaires" ADD CONSTRAINT "parent_guardian_questionnaires_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."caregiver_questionnaires" ADD CONSTRAINT "caregiver_questionnaires_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."outsider_questionnaires" ADD CONSTRAINT "outsider_questionnaires_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."facility_walkthrough_checklists" ADD CONSTRAINT "facility_walkthrough_checklists_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."initial_observation_forms" ADD CONSTRAINT "initial_observation_forms_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."guided_observations_procedures" ADD CONSTRAINT "guided_observations_procedures_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ks1_interview_questions" ADD CONSTRAINT "ks1_interview_questions_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ks2_interview_questions" ADD CONSTRAINT "ks2_interview_questions_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."peer_dynamic_observation" ADD CONSTRAINT "peer_dynamic_observation_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."parent_child_dynamic_observation" ADD CONSTRAINT "parent_child_dynamic_observation_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."comprehensive_profile_sheet" ADD CONSTRAINT "comprehensive_profile_sheet_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
