-- CreateTable
CREATE TABLE "public"."comprehensive_profile_sheet" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "childName" TEXT,
    "childAge" TEXT,
    "assessmentDate" TEXT,
    "recommendedPlacement" TEXT,
    "examiner" TEXT,
    "processingSpeedSteadyReflective" BOOLEAN NOT NULL DEFAULT false,
    "processingSpeedFlexibleAdaptive" BOOLEAN NOT NULL DEFAULT false,
    "processingSpeedRapidResponsive" BOOLEAN NOT NULL DEFAULT false,
    "workingMemoryAreaOfGrowth" BOOLEAN NOT NULL DEFAULT false,
    "workingMemoryDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "workingMemoryConsistentConfident" BOOLEAN NOT NULL DEFAULT false,
    "attentionFocusVariable" BOOLEAN NOT NULL DEFAULT false,
    "attentionFocusFocusedWithCues" BOOLEAN NOT NULL DEFAULT false,
    "attentionFocusSelfDirected" BOOLEAN NOT NULL DEFAULT false,
    "verbalReasoningExploring" BOOLEAN NOT NULL DEFAULT false,
    "verbalReasoningDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "verbalReasoningFluentCommunicator" BOOLEAN NOT NULL DEFAULT false,
    "phonologicalAwarenessExploring" BOOLEAN NOT NULL DEFAULT false,
    "phonologicalAwarenessLinking" BOOLEAN NOT NULL DEFAULT false,
    "phonologicalAwarenessConfident" BOOLEAN NOT NULL DEFAULT false,
    "visualSpatialSkillsExploring" BOOLEAN NOT NULL DEFAULT false,
    "visualSpatialSkillsDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "visualSpatialSkillsConfident" BOOLEAN NOT NULL DEFAULT false,
    "numericalPatternConcrete" BOOLEAN NOT NULL DEFAULT false,
    "numericalPatternEmergingAbstract" BOOLEAN NOT NULL DEFAULT false,
    "numericalPatternFlexibleThinker" BOOLEAN NOT NULL DEFAULT false,
    "additionalCognitiveNotes" TEXT,
    "visualObserved" BOOLEAN NOT NULL DEFAULT false,
    "visualObservedEvidence" TEXT,
    "auditoryObserved" BOOLEAN NOT NULL DEFAULT false,
    "auditoryObservedEvidence" TEXT,
    "kinestheticTactileObserved" BOOLEAN NOT NULL DEFAULT false,
    "kinestheticTactileObservedEvidence" TEXT,
    "readingWritingObserved" BOOLEAN NOT NULL DEFAULT false,
    "readingWritingObservedEvidence" TEXT,
    "verbalLinguisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "verbalLinguisticObservedEvidence" TEXT,
    "logicalMathematicalObserved" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalObservedEvidence" TEXT,
    "socialInterpersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "socialInterpersonalObservedEvidence" TEXT,
    "solitaryIntrapersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "solitaryIntrapersonalObservedEvidence" TEXT,
    "multimodalObserved" BOOLEAN NOT NULL DEFAULT false,
    "multimodalObservedEvidence" TEXT,
    "linguisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "linguisticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "linguisticNotes" TEXT,
    "logicalMathematicalObservedInt" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalStronglyEvidentInt" BOOLEAN NOT NULL DEFAULT false,
    "logicalMathematicalNotesInt" TEXT,
    "spatialObserved" BOOLEAN NOT NULL DEFAULT false,
    "spatialStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "spatialNotes" TEXT,
    "bodilyKinestheticObserved" BOOLEAN NOT NULL DEFAULT false,
    "bodilyKinestheticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "bodilyKinestheticNotes" TEXT,
    "musicalObserved" BOOLEAN NOT NULL DEFAULT false,
    "musicalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "musicalNotes" TEXT,
    "interpersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "interpersonalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "interpersonalNotes" TEXT,
    "intrapersonalObserved" BOOLEAN NOT NULL DEFAULT false,
    "intrapersonalStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "intrapersonalNotes" TEXT,
    "naturalisticObserved" BOOLEAN NOT NULL DEFAULT false,
    "naturalisticStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "naturalisticNotes" TEXT,
    "existentialObserved" BOOLEAN NOT NULL DEFAULT false,
    "existentialStronglyEvident" BOOLEAN NOT NULL DEFAULT false,
    "existentialNotes" TEXT,
    "summaryInsightLearnerType" TEXT,
    "summaryInsightLearningEnvironments" TEXT,
    "selfRegulationEmerging" BOOLEAN NOT NULL DEFAULT false,
    "selfRegulationDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "selfRegulationStrong" BOOLEAN NOT NULL DEFAULT false,
    "selfRegulationNotesEvidence" TEXT,
    "emotionalIntelligenceEmerging" BOOLEAN NOT NULL DEFAULT false,
    "emotionalIntelligenceDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "emotionalIntelligenceStrong" BOOLEAN NOT NULL DEFAULT false,
    "emotionalIntelligenceNotesEvidence" TEXT,
    "socialCommunicationEmerging" BOOLEAN NOT NULL DEFAULT false,
    "socialCommunicationDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "socialCommunicationStrong" BOOLEAN NOT NULL DEFAULT false,
    "socialCommunicationNotesEvidence" TEXT,
    "cognitiveFlexibilityEmerging" BOOLEAN NOT NULL DEFAULT false,
    "cognitiveFlexibilityDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "cognitiveFlexibilityStrong" BOOLEAN NOT NULL DEFAULT false,
    "cognitiveFlexibilityNotesEvidence" TEXT,
    "resilienceConfidenceEmerging" BOOLEAN NOT NULL DEFAULT false,
    "resilienceConfidenceDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "resilienceConfidenceStrong" BOOLEAN NOT NULL DEFAULT false,
    "resilienceConfidenceNotesEvidence" TEXT,
    "creativityExpressionEmerging" BOOLEAN NOT NULL DEFAULT false,
    "creativityExpressionDeveloping" BOOLEAN NOT NULL DEFAULT false,
    "creativityExpressionStrong" BOOLEAN NOT NULL DEFAULT false,
    "creativityExpressionNotesEvidence" TEXT,
    "softSkillSummaryNotes" TEXT,
    "englishCurrentLevel" TEXT,
    "englishNotes" TEXT,
    "mathsCurrentLevel" TEXT,
    "mathsNotes" TEXT,
    "scienceCurrentLevel" TEXT,
    "scienceNotes" TEXT,
    "technologyUseLow" BOOLEAN NOT NULL DEFAULT false,
    "technologyUseModerate" BOOLEAN NOT NULL DEFAULT false,
    "technologyUseHigh" BOOLEAN NOT NULL DEFAULT false,
    "technologyUseExceptional" BOOLEAN NOT NULL DEFAULT false,
    "academicNotes" TEXT,
    "zonesADPreferredZones" TEXT,
    "zonesADSelfDirectedOrReliant" TEXT,
    "zonesADResponseToChallenge" TEXT,
    "zonesADEvidenceDominantIntelligence" TEXT,
    "peerSessionInitiateOrFollow" TEXT,
    "peerSessionRoleAdopted" TEXT,
    "peerSessionConflictHandled" TEXT,
    "parentChildEmotionalTone" TEXT,
    "parentChildFacilitativeVsDirective" TEXT,
    "parentChildResponseWorkingSolo" TEXT,
    "ks1Score" INTEGER,
    "ks1InterpretationEmerging" BOOLEAN NOT NULL DEFAULT false,
    "ks1InterpretationBasic" BOOLEAN NOT NULL DEFAULT false,
    "ks1InterpretationStrong" BOOLEAN NOT NULL DEFAULT false,
    "ks1InterpretationExceptional" BOOLEAN NOT NULL DEFAULT false,
    "ks1SuggestedAction" TEXT,
    "ks1ScoreRange1325Action" TEXT,
    "ks1ScoreRange2640Action" TEXT,
    "ks1ScoreRange4155Action" TEXT,
    "ks1ScoreRange5665Action" TEXT,
    "ks2Score" INTEGER,
    "ks2InterpretationEmerging" BOOLEAN NOT NULL DEFAULT false,
    "ks2InterpretationBasic" BOOLEAN NOT NULL DEFAULT false,
    "ks2InterpretationStrong" BOOLEAN NOT NULL DEFAULT false,
    "ks2InterpretationExceptional" BOOLEAN NOT NULL DEFAULT false,
    "ks2SuggestedAction" TEXT,
    "ks2ScoreRange2044Action" TEXT,
    "ks2ScoreRange4569Action" TEXT,
    "ks2ScoreRange7089Action" TEXT,
    "ks2ScoreRange9095Action" TEXT,
    "qualitativeInsightsVerbalResponses" TEXT,
    "aiCurriculumEntryPoint" TEXT,
    "peerEngagementGroupLearning" BOOLEAN NOT NULL DEFAULT false,
    "peerEngagementNeedsScaffolding" BOOLEAN NOT NULL DEFAULT false,
    "peerEngagementMonitorConflict" BOOLEAN NOT NULL DEFAULT false,
    "mentorshipLeadershipPotential" BOOLEAN NOT NULL DEFAULT false,
    "mentorshipRecommendOneOnOne" BOOLEAN NOT NULL DEFAULT false,
    "mentorshipNotApplicable" BOOLEAN NOT NULL DEFAULT false,
    "homeSupportTips" TEXT,
    "finalSummaryStrengths" TEXT,
    "finalSummaryApproaches" TEXT,
    "finalSummaryTargetedSupport" TEXT,
    "compiledBy" TEXT,
    "compiledDate" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "comprehensive_profile_sheet_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "comprehensive_profile_sheet_applicationId_key" ON "public"."comprehensive_profile_sheet"("applicationId");

-- AddForeignKey
ALTER TABLE "public"."comprehensive_profile_sheet" ADD CONSTRAINT "comprehensive_profile_sheet_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "public"."applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
